name: brew test-bot

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            build_mode: test-bot
          - os: macos-15-intel
            build_mode: manual-bottle
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      checks: read
      contents: read
      packages: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@a657b8b0cd35d0f65cce41fce9b24cf054b49869
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax

      - name: Encode the registry token
        id: registry-token
        if: github.event_name == 'pull_request'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          encoded_token="$(printf '%s' "$TOKEN" | base64 | tr -d '\n')"
          echo "::add-mask::$encoded_token"
          echo "token=$encoded_token" >> "$GITHUB_OUTPUT"

      - name: Build and test Formulae
        if: github.event_name == 'pull_request' && matrix.build_mode == 'test-bot'
        env:
          HOMEBREW_DOCKER_REGISTRY_TOKEN: ${{ steps.registry-token.outputs.token }}
        run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/regulusleow/homebrew-tap

      - name: Build and test Formula on Intel
        if: github.event_name == 'pull_request' && matrix.build_mode == 'manual-bottle'
        run: |
          brew install node@22
          brew install --build-bottle regulusleow/tap/astrolabe
          brew test regulusleow/tap/astrolabe
          brew audit --new regulusleow/tap/astrolabe
          brew bottle --json \
            --root-url=https://ghcr.io/v2/regulusleow/homebrew-tap \
            regulusleow/tap/astrolabe

      - name: Upload bottles as artifacts
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
          if-no-files-found: error
